CREATE MATERIALIZED VIEW public.opponent_player_career_high_aggregate AS

 SELECT opponent_player_career_high.player_id,
    (jsonb_agg(jsonb_build_object('stat_value', opponent_player_career_high.stat_value, 'game_id', opponent_player_career_high.game_id, 'opponent_team_name', opponent_player_career_high.opponent_team_name, 'opponent_team_slug', opponent_player_career_high.opponent_team_slug, 'game_date', opponent_player_career_high.game_date)) FILTER (WHERE opponent_player_career_high.category = 'points'::text))[0] AS points,
    (jsonb_agg(jsonb_build_object('stat_value', opponent_player_career_high.stat_value, 'game_id', opponent_player_career_high.game_id, 'opponent_team_name', opponent_player_career_high.opponent_team_name, 'opponent_team_slug', opponent_player_career_high.opponent_team_slug, 'game_date', opponent_player_career_high.game_date)) FILTER (WHERE opponent_player_career_high.category = 'rebounds'::text))[0] AS rebounds,
    (jsonb_agg(jsonb_build_object('stat_value', opponent_player_career_high.stat_value, 'game_id', opponent_player_career_high.game_id, 'opponent_team_name', opponent_player_career_high.opponent_team_name, 'opponent_team_slug', opponent_player_career_high.opponent_team_slug, 'game_date', opponent_player_career_high.game_date)) FILTER (WHERE opponent_player_career_high.category = 'assists'::text))[0] AS assists,
    (jsonb_agg(jsonb_build_object('stat_value', opponent_player_career_high.stat_value, 'game_id', opponent_player_career_high.game_id, 'opponent_team_name', opponent_player_career_high.opponent_team_name, 'opponent_team_slug', opponent_player_career_high.opponent_team_slug, 'game_date', opponent_player_career_high.game_date)) FILTER (WHERE opponent_player_career_high.category = 'steals'::text))[0] AS steals,
    (jsonb_agg(jsonb_build_object('stat_value', opponent_player_career_high.stat_value, 'game_id', opponent_player_career_high.game_id, 'opponent_team_name', opponent_player_career_high.opponent_team_name, 'opponent_team_slug', opponent_player_career_high.opponent_team_slug, 'game_date', opponent_player_career_high.game_date)) FILTER (WHERE opponent_player_career_high.category = 'blocks'::text))[0] AS blocks,
    (jsonb_agg(jsonb_build_object('stat_value', opponent_player_career_high.stat_value, 'game_id', opponent_player_career_high.game_id, 'opponent_team_name', opponent_player_career_high.opponent_team_name, 'opponent_team_slug', opponent_player_career_high.opponent_team_slug, 'game_date', opponent_player_career_high.game_date)) FILTER (WHERE opponent_player_career_high.category = 'field_goals_made'::text))[0] AS field_goals_made,
    (jsonb_agg(jsonb_build_object('stat_value', opponent_player_career_high.stat_value, 'game_id', opponent_player_career_high.game_id, 'opponent_team_name', opponent_player_career_high.opponent_team_name, 'opponent_team_slug', opponent_player_career_high.opponent_team_slug, 'game_date', opponent_player_career_high.game_date)) FILTER (WHERE opponent_player_career_high.category = 'three_pointers_made'::text))[0] AS three_pointers_made,
    (jsonb_agg(jsonb_build_object('stat_value', opponent_player_career_high.stat_value, 'game_id', opponent_player_career_high.game_id, 'opponent_team_name', opponent_player_career_high.opponent_team_name, 'opponent_team_slug', opponent_player_career_high.opponent_team_slug, 'game_date', opponent_player_career_high.game_date)) FILTER (WHERE opponent_player_career_high.category = 'free_throws_made'::text))[0] AS free_throws_made,
    (jsonb_agg(jsonb_build_object('stat_value', opponent_player_career_high.stat_value, 'game_id', opponent_player_career_high.game_id, 'opponent_team_name', opponent_player_career_high.opponent_team_name, 'opponent_team_slug', opponent_player_career_high.opponent_team_slug, 'game_date', opponent_player_career_high.game_date)) FILTER (WHERE opponent_player_career_high.category = 'efficiency'::text))[0] AS efficiency
   
FROM opponent_player_career_high
  
GROUP BY opponent_player_career_high.player_id;